# 修改hostname
# test 3
# on push 
# add code review
# review test 
# branch f1 
name: GitHub Actions before 

on:
  pull_request:
    branches:
      - master
  push:
     branches:
       - f1

jobs:
  myfirstjob:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      run: |
            echo "Welcome" 

