
name: GitHub Actions before 


on: 
  pull_reqeust: 
    branches: 
      - master

jobs:
  myfirstjob:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      run: |
	hostname 

